<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Alco.Profiler.Weaver.Fixture</RootNamespace>
    <AssemblyName>Alco.Profiler.Weaver.Fixture</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DebugType>portable</DebugType>
    <MethodProfilerInfrastructureProject>true</MethodProfilerInfrastructureProject>
  </PropertyGroup>
</Project>
