<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Alco.World3D</RootNamespace>
    <AssemblyName>Alco.World3D</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alco.Engine\Alco.Engine.csproj" />
    <InternalsVisibleTo Include="$(AssemblyName).Test" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)Assets\**\*.*">
      <Link>Assets/%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
