trigger:
- main

resources:
- repo: self


stages:
- stage: Build
  jobs:
  - job: Build
    timeoutInMinutes: 30
  
    variables:
      macOS: macOS-latest
      linux: Ubuntu-latest
      windows: windows-2022
      outputDir: '$(Build.SourcesDirectory)/Bin'
  
    strategy:
      matrix:
        Windows_Debug: 
          image: ${{ variables.windows }}
          mode: Debug
        Windows_Release:
          image: ${{ variables.windows }}
          mode: Release
        Linux_Debug:
          image: ${{ variables.linux }}
          mode: Debug
        Linux_Release:
          image: ${{ variables.linux }}
          mode: Release
        MacOS_Debug:
          image: ${{ variables.macOS }}
          mode: Debug
        MacOS_Release:
          image: ${{ variables.macOS }}
          mode: Release
    
    pool:
      vmImage: $(image)

    steps:
    - checkout: self
      clean: true
      submodules: true
    
    - task: UseDotNet@2
      inputs:
        version: '8.x'
      
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/Vocore.Test.csproj'
        arguments: '--configuration $(mode)'
        publishTestResults: true
      displayName: 'Test'
    
    - script: dotnet build --configuration $(mode) --output $(outputDir)
      displayName: 'Build'

    - script: ls -R $(outputDir)
      displayName: 'List files'
          

