<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <MethodProfilerInfrastructureProject>true</MethodProfilerInfrastructureProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Src\Alco.Profiler\Alco.Profiler.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="NUnit.Analyzers" Version="3.6.1" />
  </ItemGroup>
</Project>
