<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Alco.Editor.App</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA2265;CS8625</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alco.Editor\Alco.Editor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Demo.alco">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DemoAssets\**\*.*">
      <Link>DemoAssets/%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
