<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Alco.Particles</RootNamespace>
    <AssemblyName>Alco.Particles</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alco.Rendering\Alco.Rendering.csproj" />
    <ProjectReference Include="..\Alco.IO\Alco.IO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)Assets\**\*.*">
      <Link>Assets/%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
