<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <UseAlcoGpu>true</UseAlcoGpu>

    <DefineConstants Condition="'$(UseAlcoGpu)' == 'true'">$(DefineConstants);USE_ALCO_GPU</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AlcoGpu\**\*" Condition="'$(UseAlcoGpu)' != 'true'" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseAlcoGpu)' == 'true'">
    <Content Include="$(MSBuildThisFileDirectory)\runtimes\$(RuntimeIdentifier)\native\**">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Visible>False</Visible>
    </Content>
  </ItemGroup>

</Project>
