<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <UseWebGPU>true</UseWebGPU>

    <DefineConstants Condition="'$(UseWebGPU)' == 'true'">$(DefineConstants);USE_WEBGPU</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="WGPU\**\*" Condition="'$(UseWebGPU)' != 'true'" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Vulkan" Version="1.8.5" />
    <PackageReference Include="Vortice.VulkanMemoryAllocator" Version="1.4.3" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseWebGPU)' == 'true'">
    <Content Include="$(MSBuildThisFileDirectory)\runtimes\$(RuntimeIdentifier)\native\**">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Visible>False</Visible>
    </Content>
  </ItemGroup>

</Project>
