<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <ProjectReference Include="..\..\Benchmark\BenchmarkFramework\BenchmarkFramework.csproj" />

    <ProjectReference Include="..\..\Src\Alco\Alco.csproj" />
    <ProjectReference Include="..\..\Src\Alco.Rendering\Alco.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Files\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Include="libpng16.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
