<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Src\Alco.Engine\Alco.Engine.csproj" />
    <ProjectReference Include="..\..\Src\Alco.ImGUI\Alco.ImGUI.csproj" />
    <ProjectReference Include="..\..\Src\Alco.LLM\Alco.LLM.csproj" />
    <ProjectReference Include="..\..\Src\Alco.Particles\Alco.Particles.csproj" />
  </ItemGroup>

</Project>
